import Head from 'next/head';
import Navbar from '../element/navbar/navbar';
import Footer from '../element/footer/footer';
import PropTypes from 'prop-types';
export default function Layout({ children, title }){
    return(
        <div>
            <Head>
                <meta name="viewport" content="width=device-width, initial-scale=1.0" />
                <title>JobQoo | {title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header>
                <Navbar />
            </header>
            <main>
                { children }
            </main>
            <Footer />
        </div>
    )
}

Layout.propType = {
    children:PropTypes.node,
    title:PropTypes.title
}