import Head from 'next/head';
import Navbar from '../element/navbar/navbar';
export default function Layout({ children, title }){
    return(
        <div>
            <Head>
                <title>JobQoo | {title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header>
                <Navbar />
            </header>
            <main>
                { children }
            </main>
        </div>
    )
}